<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download PDF</name>
   <tag></tag>
   <elementGuidId>8cadbab7-bbed-4fe9-88b5-04e3381f4d29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mainContent&quot;]/div/div/div/div/div/div/div/div/div[2]/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@href = 'https://www.firstrepublic.com/~/media/frb/documents/pdfs/annual-report/frb_ar16_final_pdf_file_2017-05.ashx']) = count(//*[@href = 'https://www.firstrepublic.com/~/media/frb/documents/pdfs/annual-report/frb_ar16_final_pdf_file_2017-05.ashx'])][count(. | //*[text() = 'Download PDF']) = count(//*[text() = 'Download PDF'])][count(. | id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 medium-12 large-12 columns content&quot;]/div[@class=&quot;annual-report&quot;]/div[@class=&quot;annual-report__item--featured&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content columns annual-report__item--media-overlay&quot;]/div[@class=&quot;annual-report__item--links&quot;]/ul[@class=&quot;icon-buttons component&quot;]/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link&quot;]) = count(id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 medium-12 large-12 columns content&quot;]/div[@class=&quot;annual-report&quot;]/div[@class=&quot;annual-report__item--featured&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content columns annual-report__item--media-overlay&quot;]/div[@class=&quot;annual-report__item--links&quot;]/ul[@class=&quot;icon-buttons component&quot;]/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.firstrepublic.com/~/media/frb/documents/pdfs/annual-report/frb_ar16_final_pdf_file_2017-05.ashx</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-buttons--link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download PDF</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 medium-12 large-12 columns content&quot;]/div[@class=&quot;annual-report&quot;]/div[@class=&quot;annual-report__item--featured&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content columns annual-report__item--media-overlay&quot;]/div[@class=&quot;annual-report__item--links&quot;]/ul[@class=&quot;icon-buttons component&quot;]/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
