<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sun</name>
   <tag></tag>
   <elementGuidId>2ede8c04-8c64-4996-a1f8-347aead7c62b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hours-table-list--day</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sun:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;location-detail&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 medium-4 large-3&quot;]/div[@class=&quot;location-detail--section location-detail__hours&quot;]/div[@class=&quot;hours-table&quot;]/ul[@class=&quot;hours-table-list clearfix&quot;]/li[7]/div[@class=&quot;hours-table-list--day&quot;]</value>
   </webElementProperties>
</WebElementEntity>
