<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Open</name>
   <tag></tag>
   <elementGuidId>9e4ff3e1-a02f-422c-a8c9-7342ceb6e56e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-bold-sans</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;location-detail&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 medium-4 large-3&quot;]/div[@class=&quot;location-detail--section location-detail__hours&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;location-detail__hours-status&quot;]/h4[@class=&quot;text-bold-sans&quot;]</value>
   </webElementProperties>
</WebElementEntity>
