<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_More</name>
   <tag></tag>
   <elementGuidId>7b02326a-5507-4e91-b13b-7744337d4624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href,'/about-us/testimonials/')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 medium-8 large-9 columns content&quot;]/div[@class=&quot;featured-testimonial__component content paddingB20&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;large-5 columns featured-testimonial__text-container&quot;]/div[@class=&quot;featured-testimonial__buttons&quot;]/a[@class=&quot;more-link&quot;]) = count(id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 medium-8 large-9 columns content&quot;]/div[@class=&quot;featured-testimonial__component content paddingB20&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;large-5 columns featured-testimonial__text-container&quot;]/div[@class=&quot;featured-testimonial__buttons&quot;]/a[@class=&quot;more-link&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/about-us/testimonials/e-david-ellington?intcmp=testimonial;non-campaign</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>more-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Learn more about E. David Ellington's experience with First Republic.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ta-intcmp-loc</name>
      <type>Main</type>
      <value>testimonial</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ta-intcmp-id</name>
      <type>Main</type>
      <value>non-campaign</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    More
                                </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 medium-8 large-9 columns content&quot;]/div[@class=&quot;featured-testimonial__component content paddingB20&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;large-5 columns featured-testimonial__text-container&quot;]/div[@class=&quot;featured-testimonial__buttons&quot;]/a[@class=&quot;more-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
