<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue_Twitter</name>
   <tag></tag>
   <elementGuidId>035fd028-ea51-450d-ba86-62547fc61e3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;externalLinkModal&quot;]/div/div/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@href = 'https://twitter.com/share?text=Meant To Be%3a How to Know if You and Student Loan Refinancing Are a Potential Match&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match&amp;via=firstrepublic']) = count(//*[@href = 'https://twitter.com/share?text=Meant To Be%3a How to Know if You and Student Loan Refinancing Are a Potential Match&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match&amp;via=firstrepublic'])][count(. | id(&quot;externalLinkModal&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 medium-8 large-6 medium-centered&quot;]/div[@class=&quot;content rich-text&quot;]/div[@class=&quot;row collapse&quot;]/div[@class=&quot;columns small-12 medium-6 text-right&quot;]/a[@class=&quot;button btn-continue open-share-window&quot;]) = count(id(&quot;externalLinkModal&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 medium-8 large-6 medium-centered&quot;]/div[@class=&quot;content rich-text&quot;]/div[@class=&quot;row collapse&quot;]/div[@class=&quot;columns small-12 medium-6 text-right&quot;]/a[@class=&quot;button btn-continue open-share-window&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-continue open-share-window</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Continue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://twitter.com/share?text=Meant To Be%3a How to Know if You and Student Loan Refinancing Are a Potential Match&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match&amp;via=firstrepublic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;externalLinkModal&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 medium-8 large-6 medium-centered&quot;]/div[@class=&quot;content rich-text&quot;]/div[@class=&quot;row collapse&quot;]/div[@class=&quot;columns small-12 medium-6 text-right&quot;]/a[@class=&quot;button btn-continue open-share-window&quot;]</value>
   </webElementProperties>
</WebElementEntity>
