<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LinkedIn</name>
   <tag></tag>
   <elementGuidId>0333339b-b4d8-41eb-8740-5518518631c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;shareSoicalLayout&quot;]/li[4]/a[contains(text(),'LinkedIn')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@href = 'http://www.linkedin.com/shareArticle?mini=true&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match']) = count(//*[@href = 'http://www.linkedin.com/shareArticle?mini=true&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match'])][count(. | //*[text() = 'LinkedIn']) = count(//*[text() = 'LinkedIn'])][count(. | id(&quot;shareSoicalLayout&quot;)/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link social-sharing share-popup external-link&quot;]) = count(id(&quot;shareSoicalLayout&quot;)/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link social-sharing share-popup external-link&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.linkedin.com/shareArticle?mini=true&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-buttons--link social-sharing share-popup external-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ttm</name>
      <type>Main</type>
      <value>linkedin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Share Meant To Be: How to Know if You and Student Loan Refinancing Are a Potential Match via LinkedIn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reveal-id</name>
      <type>Main</type>
      <value>externalLinkModal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LinkedIn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shareSoicalLayout&quot;)/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link social-sharing share-popup external-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
