<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Twitter</name>
   <tag></tag>
   <elementGuidId>84d27b4b-3c84-4340-9ff3-8e9449e29e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;shareSoicalLayout&quot;]/li[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@href = 'https://twitter.com/share?text=Meant To Be%3a How to Know if You and Student Loan Refinancing Are a Potential Match&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match&amp;via=firstrepublic']) = count(//*[@href = 'https://twitter.com/share?text=Meant To Be%3a How to Know if You and Student Loan Refinancing Are a Potential Match&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match&amp;via=firstrepublic'])][count(. | //*[text() = 'Twitter']) = count(//*[text() = 'Twitter'])][count(. | id(&quot;shareSoicalLayout&quot;)/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link social-sharing share-popup external-link&quot;]) = count(id(&quot;shareSoicalLayout&quot;)/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link social-sharing share-popup external-link&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://twitter.com/share?text=Meant To Be%3a How to Know if You and Student Loan Refinancing Are a Potential Match&amp;url=https://www.firstrepublic.com/articles-insights/life-money/grow-your-wealth/meant-to-be-how-to-know-if-you-and-student-loan-refinancing-are-a-potential-match&amp;via=firstrepublic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-buttons--link social-sharing share-popup external-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ttm</name>
      <type>Main</type>
      <value>twitter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Share Meant To Be: How to Know if You and Student Loan Refinancing Are a Potential Match via Twitter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reveal-id</name>
      <type>Main</type>
      <value>externalLinkModal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Twitter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shareSoicalLayout&quot;)/li[@class=&quot;icon-buttons--item&quot;]/a[@class=&quot;icon-buttons--link social-sharing share-popup external-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
