<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Geary</name>
   <tag></tag>
   <elementGuidId>e8109373-722a-4951-a5cd-79f14cc93243</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>extend-h4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Geary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;page-constraint&quot;]/div[@class=&quot;locations-landing-wrapper&quot;]/div[@class=&quot;row collapse&quot;]/div[@class=&quot;columns small-12 medium-5 large-4 left&quot;]/div[@class=&quot;locations-list--container&quot;]/ul[@class=&quot;locations-list&quot;]/li[@class=&quot;row collapse locations-list--item&quot;]/div[@class=&quot;columns small-10&quot;]/div[@class=&quot;locations-list-data&quot;]/div[@class=&quot;locations-list--title&quot;]/h2[@class=&quot;extend-h4&quot;]</value>
   </webElementProperties>
</WebElementEntity>
