<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_locationSearchTerm</name>
   <tag></tag>
   <elementGuidId>1a039a16-1c80-46f2-9908-d53eb3856c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[count(. | //*[@name = 'locationSearchTerm']) = count(//*[@name = 'locationSearchTerm'])][count(. | //*[@id = 'locationSearchTerm']) = count(//*[@id = 'locationSearchTerm'])][count(. | id(&quot;locationSearchTerm&quot;)) = count(id(&quot;locationSearchTerm&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>locationSearchTerm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationSearchTerm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterTestimonial</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationSearchTerm&quot;)</value>
   </webElementProperties>
</WebElementEntity>
