<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Details</name>
   <tag></tag>
   <elementGuidId>7a858196-2ece-470b-9c98-c2ef050e43cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wffmbf8158ab32bb4791ac615edee07cdf99_Sections_6__Fields_0__Value&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//textarea[count(. | //*[@id = 'wffmbf8158ab32bb4791ac615edee07cdf99_Sections_5__Fields_0__Value']) = count(//*[@id = 'wffmbf8158ab32bb4791ac615edee07cdf99_Sections_5__Fields_0__Value'])][count(. | //*[@name = 'wffmbf8158ab32bb4791ac615edee07cdf99.Sections[5].Fields[0].Value']) = count(//*[@name = 'wffmbf8158ab32bb4791ac615edee07cdf99.Sections[5].Fields[0].Value'])][count(. | id(&quot;wffmbf8158ab32bb4791ac615edee07cdf99_Sections_5__Fields_0__Value&quot;)) = count(id(&quot;wffmbf8158ab32bb4791ac615edee07cdf99_Sections_5__Fields_0__Value&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Are there any details you would like us to know? (optional) must be a string with a minimum length of 0 and a maximum length of 256.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>256</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wffmbf8158ab32bb4791ac615edee07cdf99_Sections_5__Fields_0__Value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wffmbf8158ab32bb4791ac615edee07cdf99.Sections[5].Fields[0].Value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wffmbf8158ab32bb4791ac615edee07cdf99_Sections_5__Fields_0__Value&quot;)</value>
   </webElementProperties>
</WebElementEntity>
