<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>30b20bdd-23b9-43e1-83b8-021eba433d17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[count(. | //*[@src = '/~/media/frb/images/fund-your-dreams/icon_check_mark.ashx?h=51&amp;la=en&amp;w=51&amp;hash=2F65D6F5FF31F908CD9CC6954CAA7959D7B40DE2']) = count(//*[@src = '/~/media/frb/images/fund-your-dreams/icon_check_mark.ashx?h=51&amp;la=en&amp;w=51&amp;hash=2F65D6F5FF31F908CD9CC6954CAA7959D7B40DE2'])][count(. | //*[@width = '51']) = count(//*[@width = '51'])][count(. | //*[@height = '51']) = count(//*[@height = '51'])][count(. | id(&quot;section0&quot;)/div[@class=&quot;fp-tableCell&quot;]/div[@class=&quot;section-content-wrapper row&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;aio-estimator-wrapper-new fullPage&quot;]/div[@class=&quot;aio-estimator-new&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 medium-6 medium-push-6 large-6 xlarge-5 xlarge-push-7 form-columns&quot;]/div[@class=&quot;aio-steps aio-step3 hide&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 step-icon-wrapper&quot;]/span[1]/img[1]) = count(id(&quot;section0&quot;)/div[@class=&quot;fp-tableCell&quot;]/div[@class=&quot;section-content-wrapper row&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;aio-estimator-wrapper-new fullPage&quot;]/div[@class=&quot;aio-estimator-new&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 medium-6 medium-push-6 large-6 xlarge-5 xlarge-push-7 form-columns&quot;]/div[@class=&quot;aio-steps aio-step3 hide&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 step-icon-wrapper&quot;]/span[1]/img[1])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/~/media/frb/images/fund-your-dreams/icon_check_mark.ashx?h=51&amp;la=en&amp;w=51&amp;hash=2F65D6F5FF31F908CD9CC6954CAA7959D7B40DE2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>51</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>51</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section0&quot;)/div[@class=&quot;fp-tableCell&quot;]/div[@class=&quot;section-content-wrapper row&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;aio-estimator-wrapper-new fullPage&quot;]/div[@class=&quot;aio-estimator-new&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 medium-6 medium-push-6 large-6 xlarge-5 xlarge-push-7 form-columns&quot;]/div[@class=&quot;aio-steps aio-step3 hide&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;columns small-12 step-icon-wrapper&quot;]/span[1]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
